controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

home:
  path: /
  controller: App\Controller\HomeController::index

fallback:
  path: /{url}
  controller: App\Controller\HomeController::index
  requirements:
    url: "^(?!_profiler|_wdt|api).*$"
